name: build_run_test

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print basic job parameters
        run: |
          echo "ğŸ‰ Job triggered by ${{ github.event_name }} event."
          echo "ğŸ§ Job running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” Branch: ${{ github.ref }}; repository: ${{ github.repository }}."
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.14'
      - name: Upgrade pip and install packages
        run: |
          pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Print out python version and packages
        run: |
          python --version
          pip freeze
      - name: Convert test notebook
        run: |
          jupyter nbconvert --execute --to html 01_test_notebook.ipynb
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: knutzk/ml-workshop:latest
